name: 'serverpod_riverpod_template_flutter'
version: '1.0.0+1'
publish_to: none
environment: 
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'
description: A new Flutter project with Serverpod.
dependencies: 
  cupertino_icons: '^1.0.5'
  flutter: 
    sdk: flutter
  flutter_hooks: '^0.20.5'
  flutter_localizations: 
    sdk: flutter
  go_router: '^14.2.0'
  hooks_riverpod: '^2.5.1'
  intl: any
  riverpod_annotation: '^2.3.5'
  serverpod_flutter: 1.2.2
  serverpod_riverpod_template_client: 
    path: '../serverpod_riverpod_template_client'
  shared_preferences: '^2.2.3'
dev_dependencies: 
  build_runner: '^2.4.9'
  build_verify: '^3.1.0'
  custom_lint: '^0.6.4'
  flutter_gen_runner: '^5.6.0'
  flutter_lints: '^3.0.0'
  flutter_test: 
    sdk: flutter
  go_router_builder: '^2.7.0'
  pubspec_dependency_sorter: '^1.0.4'
  riverpod_generator: '^2.4.0'
  riverpod_lint: '^2.3.10'
  very_good_analysis: '^5.1.0'
flutter: 
  uses-material-design: true
  generate: true
